name: Discord Webhook Notify

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "**${{ github.actor }}** pushed to `${{ github.ref_name }}`: `${{ github.event.head_commit.message }}`"
